apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    name: pi
    session-time: '2019-06-27 13:40:00'
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  activeDeadlineSeconds: 60
  backoffLimit: 0
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 0
